### ISSUE TITLE
Use video title as default description if video do not have description or longDescription

### ISSUE THREAD

**Issue by lanmengyujing** [brightcove/videojs-schema#23]
# Overview
In some cases, Videos in Brightcove account do not have either description or long description in the mediainfo.
Our team has quite a lot of videos in Brightcove cloud that do not have descriptions and long descriptions. However, In Google Video schema Object, description of video is required. See detail here https://developers.google.com/search/docs/data-types/videohttps://developers.google.com/search/docs/data-types/video
When we use this plugin to generate Video Schema Object and test the result in Google Rich Results https://search.google.com/test/rich-results, it will fail to pass the validation.

# In Scope

- [ ] Default to video title if video do not have long description and description

# Technical Approach

Change one line of the plugin to default to video title if description is not available
```
if (options.preferLongDescription) {    
  ld.description = this.mediainfo.longDescription || this.mediainfo.description || this.mediainfo.name;   
 }  else {   
   ld.description = this.mediainfo.description || this.mediainfo.name;   
}
```

**Comment by mister-ben** [comment]
Implemented in #24
